server:
  port: 9000
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: test
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver